spring:
  cloud:
    stream:
      function:
        definition: activeDomainConsumer 

      bindings:
        activeDomainConsumer-in-0:
          destination: active.web-domains

      kafka:
        bindings:
          activeDomainConsumer-in-0:
            consumer:
              configuration:
                value:
                  deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            
        binder:
          brokers:
          - localhost:9092
            
            
            
server:
  port: 8083